export const ACTIVE_BOOKING_STATUSES = ['PENDING_PAYMENT', 'CONFIRMED', 'PICKED_UP', 'RETURNED', 'COMPLETED'];
export const OWNER_TRANSITIONS = {
  CONFIRMED: ['PICKED_UP'],
  PICKED_UP: ['RETURNED'],
  RETURNED: ['COMPLETED'],
};
